trigger:
  - main

variables:
  pythonVersion: "3.10"
  azureServiceConnection: "mlops"
  webAppName: "txlu-og"

stages:
  - stage: Build_Test
    jobs:
      - job: Build
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"

          - script: |
              python -m venv venv
              source venv/bin/activate
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: "Install dependencies"

          - script: |
              source venv/bin/activate
              flake8 . --exclude=venv
            displayName: "Run linting"

          - script: |
              source venv/bin/activate
              pytest
            displayName: "Run tests"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
              replaceExistingArchive: true

          - publish: "$(Build.ArtifactStagingDirectory)/app.zip"
            artifact: drop

  - stage: Deploy
    dependsOn: Build_Test
    condition: succeeded()
    jobs:
      - deployment: DeployWebApp
        environment: production
        pool:
          vmImage: "ubuntu-latest"

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "$(azureServiceConnection)"
                    appType: "webAppLinux"
                    appName: "$(webAppName)"
                    package: "$(Pipeline.Workspace)/drop/app.zip"